### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by Chun-QiuCC** [BaiMeow/NetworkMonitor#15]
我在自己编译后端并尝试运行的时候出现了随机报
```log
2024/09/08 04:21:42 init graph
2024/09/08 04:21:42 init graph fail:contruct probe fail:invalid parse type:bird
```
和
```log
2024/09/08 04:21:42 init graph
2024/09/08 04:21:42 init graph fail:contruct probe fail:invalid fetch type:command
```
的问题，但是我的配置文件是在/backend/conf/sample.yaml上直接改的，这是我的配置文件：
```yaml
interval: 60
probeTimeout: 40
port: 7878
probe:
  R4:
    fetch:
      type: "ssh"
      host: "10.86.7.1"
      port: 22
      user: "root"
      password: "*******"
      command: "birdc show ospf state all"
    parse:
      type: "bird"
  local:
    fetch:
      type: "command"
      cmd: "birdc show ospf state all"
    parse:
      type: "bird"
tag:
  10.86.7.1:
    name: "R4"
```
